#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

GRID_NUM_ROLLOUT="${GRID_NUM_ROLLOUT:-100}"
TEACHER_TEMPERATURE="${TEACHER_TEMPERATURE:-1.0}"
ROLLOUT_TEMPERATURE="${ROLLOUT_TEMPERATURE:-1.0}"
ROLLOUT_LABEL_KEY="${ROLLOUT_LABEL_KEY-}"
APPLY_CHAT_TEMPLATE_KWARGS="${APPLY_CHAT_TEMPLATE_KWARGS:-{\"enable_thinking\": false}}"
ROLLOUT_STOP_TOKEN_IDS="${ROLLOUT_STOP_TOKEN_IDS:-151645 151643}"
TEACHER_TENSOR_PARALLEL_SIZE="${TEACHER_TENSOR_PARALLEL_SIZE:-2}"
TEACHER_DATA_PARALLEL_SIZE="${TEACHER_DATA_PARALLEL_SIZE:-1}"
EVAL_INTERVAL="${EVAL_INTERVAL:-10}"
SAVE_INTERVAL="${SAVE_INTERVAL:-20}"
LEARNING_RATE="${LEARNING_RATE:-1e-6}"
GRID_ROLLOUT_MAX_RESPONSE_LEN="${GRID_ROLLOUT_MAX_RESPONSE_LEN:-8192}"
GRID_EVAL_MAX_RESPONSE_LEN="${GRID_EVAL_MAX_RESPONSE_LEN:-8192}"
RUN_NAME="${RUN_NAME:-openthoughts-Q3-4B-Q3-1p7B-SFT-OPD-t_1p0-lr_1e-6-len_8k}"
GRID_WANDB_GROUP="${GRID_WANDB_GROUP:-${RUN_NAME}}"
EXP_NAME="${RUN_NAME}"
export GRID_NUM_ROLLOUT TEACHER_TEMPERATURE ROLLOUT_TEMPERATURE ROLLOUT_LABEL_KEY
export APPLY_CHAT_TEMPLATE_KWARGS
export ROLLOUT_STOP_TOKEN_IDS TEACHER_TENSOR_PARALLEL_SIZE TEACHER_DATA_PARALLEL_SIZE
export EVAL_INTERVAL SAVE_INTERVAL LEARNING_RATE GRID_ROLLOUT_MAX_RESPONSE_LEN GRID_EVAL_MAX_RESPONSE_LEN
export RUN_NAME EXP_NAME GRID_WANDB_GROUP

source "${SCRIPT_DIR}/launchers/common.sh"

DATA_LABEL="OpenThoughts3 OPD 30K"
DATA_ID="openthoughts3-opd-30k"
PROMPT_DATA_VALUE="${PROMPT_DATA:-${DATA_ROOT}/OpenThoughts3_opd.parquet}"

TEACHER_LABEL="Qwen3-4B"
TEACHER_ID="qwen3-4b"
TEACHER_MODEL_VALUE="${TEACHER_MODEL:-${MODEL_ROOT}/Qwen3-4B}"

STUDENT_LABEL="Qwen3-1.7B-SFT"
STUDENT_ID="qwen3-1.7b-sft"
STUDENT_MODEL_VALUE="${STUDENT_MODEL:-${MODEL_ROOT}/Qwen3-1.7B-SFT}"
REF_LOAD_VALUE="${REF_LOAD:-${MODEL_ROOT}/Qwen3-1.7B-SFT_torch_dist}"
BASE_SCRIPT="${ROOT_DIR}/scripts/launchers/run-deepmath-1.7b_Base-4b-opd.sh"
GRID_EXP_INDEX=8

grid_main "$@"
