#!/bin/bash

set -euo pipefail

GRID_SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
ROOT_DIR="$(cd -- "${GRID_SCRIPT_DIR}/../.." &>/dev/null && pwd)"

MODEL_ROOT="${MODEL_ROOT:-models}"
DATA_ROOT="${DATA_ROOT:-data}"
source "${ROOT_DIR}/scripts/runtime.sh"
if [ -n "${SLIME_ENV_BIN:-}" ]; then
   resolve_project_paths SLIME_ENV_BIN
   export SLIME_ENV_BIN PATH="${SLIME_ENV_BIN}:${PATH}"
fi
resolve_project_paths MODEL_ROOT DATA_ROOT
export MODEL_ROOT DATA_ROOT
DRY_RUN=0
GRID_TIMESTAMP="${GRID_TIMESTAMP:-$(date +%Y%m%d-%H%M%S)}"
GRID_WANDB_GROUP="${GRID_WANDB_GROUP:-opd_grid_${GRID_TIMESTAMP}}"
GRID_NUM_ROLLOUT="${GRID_NUM_ROLLOUT:-${NUM_ROLLOUT:-100}}"
GRID_WANDB_PROJECT="${GRID_WANDB_PROJECT:-slime_opd_grid}"
GRID_WANDB_ENTITY="${GRID_WANDB_ENTITY:-${WANDB_ENTITY:-}}"
GRID_ROLLOUT_MAX_RESPONSE_LEN="${GRID_ROLLOUT_MAX_RESPONSE_LEN:-${ROLLOUT_MAX_RESPONSE_LEN:-16384}}"
GRID_EVAL_MAX_RESPONSE_LEN="${GRID_EVAL_MAX_RESPONSE_LEN:-${EVAL_MAX_RESPONSE_LEN:-16384}}"
GRID_MAX_TOKENS_PER_GPU="${GRID_MAX_TOKENS_PER_GPU:-${MAX_TOKENS_PER_GPU:-8192}}"
GRID_CONTEXT_PARALLEL_SIZE="${GRID_CONTEXT_PARALLEL_SIZE:-${CONTEXT_PARALLEL_SIZE:-2}}"
GRID_ROLLOUT_BATCH_SIZE="${GRID_ROLLOUT_BATCH_SIZE:-${ROLLOUT_BATCH_SIZE:-32}}"
GRID_N_SAMPLES_PER_PROMPT="${GRID_N_SAMPLES_PER_PROMPT:-${N_SAMPLES_PER_PROMPT:-8}}"
GRID_N_SAMPLES_PER_EVAL_PROMPT="${GRID_N_SAMPLES_PER_EVAL_PROMPT:-${N_SAMPLES_PER_EVAL_PROMPT:-4}}"
GRID_GLOBAL_BATCH_SIZE="${GRID_GLOBAL_BATCH_SIZE:-${GLOBAL_BATCH_SIZE:-128}}"
GRID_TOTAL_GPUS="${GRID_TOTAL_GPUS:-${TOTAL_GPUS:-6}}"
GRID_ACTOR_NUM_GPUS_PER_NODE="${GRID_ACTOR_NUM_GPUS_PER_NODE:-${ACTOR_NUM_GPUS_PER_NODE:-4}}"
GRID_RAY_CUDA_VISIBLE_DEVICES="${GRID_RAY_CUDA_VISIBLE_DEVICES:-${RAY_CUDA_VISIBLE_DEVICES:-0,1,2,3}}"
GRID_RAY_NUM_GPUS="${GRID_RAY_NUM_GPUS:-${RAY_NUM_GPUS:-4}}"
GRID_ROLLOUT_NUM_GPUS="${GRID_ROLLOUT_NUM_GPUS:-${ROLLOUT_NUM_GPUS:-4}}"
GRID_TEACHER_NUM_GPUS="${GRID_TEACHER_NUM_GPUS:-${TEACHER_NUM_GPUS:-2}}"
GRID_TEACHER_CUDA_VISIBLE_DEVICES="${GRID_TEACHER_CUDA_VISIBLE_DEVICES:-${TEACHER_CUDA_VISIBLE_DEVICES:-4,5}}"
GRID_TEACHER_TENSOR_PARALLEL_SIZE="${GRID_TEACHER_TENSOR_PARALLEL_SIZE:-${TEACHER_TENSOR_PARALLEL_SIZE:-2}}"
GRID_TEACHER_MEM_FRACTION_STATIC="${GRID_TEACHER_MEM_FRACTION_STATIC:-${TEACHER_MEM_FRACTION_STATIC:-0.8}}"
GRID_TEACHER_TEMPERATURE="${GRID_TEACHER_TEMPERATURE:-${TEACHER_TEMPERATURE:-0}}"
GRID_ROLLOUT_TEMPERATURE="${GRID_ROLLOUT_TEMPERATURE:-${ROLLOUT_TEMPERATURE:-1.0}}"
GRID_ROLLOUT_LABEL_KEY="${GRID_ROLLOUT_LABEL_KEY-${ROLLOUT_LABEL_KEY-label}}"

grid_usage() {
   cat <<EOF
Usage: bash $0 [--dry-run]

Options:
  --dry-run  Print this experiment without launching training.

Environment:
  RUN_NAME   Optional experiment name override for EXP_NAME.
EOF
}

grid_parse_args() {
   while [ "$#" -gt 0 ]; do
      case "$1" in
         --dry-run)
            DRY_RUN=1
            shift
            ;;
         -h|--help)
            grid_usage
            exit 0
            ;;
         *)
            echo "Unknown argument: $1" >&2
            grid_usage >&2
            exit 2
            ;;
      esac
   done
}

grid_validate_experiment() {
   local required=(
      DATA_LABEL
      DATA_ID
      PROMPT_DATA_VALUE
      TEACHER_LABEL
      TEACHER_ID
      TEACHER_MODEL_VALUE
      STUDENT_LABEL
      STUDENT_ID
      STUDENT_MODEL_VALUE
      REF_LOAD_VALUE
      BASE_SCRIPT
      GRID_EXP_INDEX
   )

   local key
   for key in "${required[@]}"; do
      if [ -z "${!key:-}" ]; then
         echo "Missing required grid variable: ${key}" >&2
         exit 1
      fi
   done

   if [ $((GRID_ROLLOUT_BATCH_SIZE * GRID_N_SAMPLES_PER_PROMPT % GRID_GLOBAL_BATCH_SIZE)) -ne 0 ]; then
      echo "rollout_batch_size * n_samples_per_prompt must be divisible by global_batch_size" >&2
      exit 1
   fi
   STEPS_PER_ROLLOUT=$((GRID_ROLLOUT_BATCH_SIZE * GRID_N_SAMPLES_PER_PROMPT / GRID_GLOBAL_BATCH_SIZE))
   if [ "${STEPS_PER_ROLLOUT}" -le 0 ]; then
      echo "Invalid steps-per-rollout=${STEPS_PER_ROLLOUT}" >&2
      exit 1
   fi
   GRID_NUM_ROLLOUT_VALUE="${GRID_NUM_ROLLOUT}"
   if [ "${GRID_NUM_ROLLOUT_VALUE}" -le 0 ]; then
      echo "GRID_NUM_ROLLOUT=${GRID_NUM_ROLLOUT} must be positive" >&2
      exit 1
   fi
   GRID_ACTUAL_TRAIN_STEPS=$((GRID_NUM_ROLLOUT_VALUE * STEPS_PER_ROLLOUT))
   if [ -n "${RUN_NAME:-}" ]; then
      GRID_EXP_NAME="${RUN_NAME}"
   else
      GRID_EXP_NAME="opd_grid_data-${DATA_ID}_teacher-${TEACHER_ID}_student-${STUDENT_ID}_${GRID_TIMESTAMP}_exp$(printf "%03d" "${GRID_EXP_INDEX}")"
   fi
}

grid_print_dry_run() {
   local relative_script="${BASE_SCRIPT#${ROOT_DIR}/}"

   echo "=== [dry-run] exp_${GRID_EXP_INDEX}: Data=${DATA_LABEL} Teacher=${TEACHER_LABEL} Student=${STUDENT_LABEL} ==="
   echo "PROMPT_DATA=${PROMPT_DATA_VALUE}"
   echo "TEACHER_MODEL=${TEACHER_MODEL_VALUE}"
   echo "STUDENT_MODEL=${STUDENT_MODEL_VALUE}"
   echo "REF_LOAD=${REF_LOAD_VALUE}"
   echo "EXP_NAME=${GRID_EXP_NAME}"
   echo "WANDB_PROJECT=${GRID_WANDB_PROJECT}"
   echo "WANDB_ENTITY=${GRID_WANDB_ENTITY}"
   echo "WANDB_GROUP=${GRID_WANDB_GROUP}"
   echo "TRAIN_STEPS=${GRID_ACTUAL_TRAIN_STEPS}"
   echo "ROLLOUT_MAX_RESPONSE_LEN=${GRID_ROLLOUT_MAX_RESPONSE_LEN}"
   echo "EVAL_MAX_RESPONSE_LEN=${GRID_EVAL_MAX_RESPONSE_LEN}"
   echo "MAX_TOKENS_PER_GPU=${GRID_MAX_TOKENS_PER_GPU}"
   echo "CONTEXT_PARALLEL_SIZE=${GRID_CONTEXT_PARALLEL_SIZE}"
   echo "NUM_ROLLOUT=${GRID_NUM_ROLLOUT_VALUE}"
   echo "ROLLOUT_BATCH_SIZE=${GRID_ROLLOUT_BATCH_SIZE}"
   echo "N_SAMPLES_PER_PROMPT=${GRID_N_SAMPLES_PER_PROMPT}"
   echo "N_SAMPLES_PER_EVAL_PROMPT=${GRID_N_SAMPLES_PER_EVAL_PROMPT}"
   echo "GLOBAL_BATCH_SIZE=${GRID_GLOBAL_BATCH_SIZE}"
   echo "TOTAL_GPUS=${GRID_TOTAL_GPUS}"
   echo "ACTOR_NUM_GPUS_PER_NODE=${GRID_ACTOR_NUM_GPUS_PER_NODE}"
   echo "RAY_CUDA_VISIBLE_DEVICES=${GRID_RAY_CUDA_VISIBLE_DEVICES}"
   echo "RAY_NUM_GPUS=${GRID_RAY_NUM_GPUS}"
   echo "ROLLOUT_NUM_GPUS=${GRID_ROLLOUT_NUM_GPUS}"
   echo "TEACHER_NUM_GPUS=${GRID_TEACHER_NUM_GPUS}"
   echo "TEACHER_CUDA_VISIBLE_DEVICES=${GRID_TEACHER_CUDA_VISIBLE_DEVICES}"
   echo "TEACHER_TENSOR_PARALLEL_SIZE=${GRID_TEACHER_TENSOR_PARALLEL_SIZE}"
   echo "TEACHER_MEM_FRACTION_STATIC=${GRID_TEACHER_MEM_FRACTION_STATIC}"
   echo "TEACHER_TEMPERATURE=${GRID_TEACHER_TEMPERATURE}"
   echo "ROLLOUT_TEMPERATURE=${GRID_ROLLOUT_TEMPERATURE}"
   echo "ROLLOUT_LABEL_KEY=${GRID_ROLLOUT_LABEL_KEY}"
   for key in EVAL_INTERVAL SAVE_INTERVAL SKIP_EVAL_BEFORE_TRAIN; do
      if [ -n "${!key:-}" ]; then
         echo "${key}=${!key}"
      fi
   done
   for key in STUDENT_LOAD STUDENT_CKPT_STEP REF_CKPT_STEP TEACHER_DATA_PARALLEL_SIZE APPLY_CHAT_TEMPLATE_KWARGS ROLLOUT_STOP_TOKEN_IDS ROLLOUT_SAMPLE_FILTER_PATH DYNAMIC_SAMPLING_SAMPLE_FILTER_PATH DYNAMIC_SAMPLING_MAX_GENERATED_SAMPLES OPD_STUDENT_EOS_TOKEN_ID OPD_TEACHER_EOS_TOKEN_ID; do
      if [ -n "${!key:-}" ]; then
         echo "${key}=${!key}"
      fi
   done
   echo "bash ${relative_script}"
}

grid_run_experiment() {
   PROMPT_DATA="${PROMPT_DATA_VALUE}" \
   TEACHER_MODEL="${TEACHER_MODEL_VALUE}" \
   STUDENT_MODEL="${STUDENT_MODEL_VALUE}" \
   REF_LOAD="${REF_LOAD_VALUE}" \
   EXP_NAME="${GRID_EXP_NAME}" \
   WANDB_PROJECT="${GRID_WANDB_PROJECT}" \
   WANDB_TEAM="${GRID_WANDB_ENTITY}" \
   WANDB_ENTITY="${GRID_WANDB_ENTITY}" \
   WANDB_GROUP="${GRID_WANDB_GROUP}" \
   ROLLOUT_MAX_RESPONSE_LEN="${GRID_ROLLOUT_MAX_RESPONSE_LEN}" \
   EVAL_MAX_RESPONSE_LEN="${GRID_EVAL_MAX_RESPONSE_LEN}" \
   MAX_TOKENS_PER_GPU="${GRID_MAX_TOKENS_PER_GPU}" \
   CONTEXT_PARALLEL_SIZE="${GRID_CONTEXT_PARALLEL_SIZE}" \
   ROLLOUT_BATCH_SIZE="${GRID_ROLLOUT_BATCH_SIZE}" \
   N_SAMPLES_PER_PROMPT="${GRID_N_SAMPLES_PER_PROMPT}" \
   N_SAMPLES_PER_EVAL_PROMPT="${GRID_N_SAMPLES_PER_EVAL_PROMPT}" \
   GLOBAL_BATCH_SIZE="${GRID_GLOBAL_BATCH_SIZE}" \
   TOTAL_GPUS="${GRID_TOTAL_GPUS}" \
   ACTOR_NUM_GPUS_PER_NODE="${GRID_ACTOR_NUM_GPUS_PER_NODE}" \
   RAY_CUDA_VISIBLE_DEVICES="${GRID_RAY_CUDA_VISIBLE_DEVICES}" \
   RAY_NUM_GPUS="${GRID_RAY_NUM_GPUS}" \
   ROLLOUT_NUM_GPUS="${GRID_ROLLOUT_NUM_GPUS}" \
   TEACHER_NUM_GPUS="${GRID_TEACHER_NUM_GPUS}" \
   TEACHER_CUDA_VISIBLE_DEVICES="${GRID_TEACHER_CUDA_VISIBLE_DEVICES}" \
   TEACHER_TENSOR_PARALLEL_SIZE="${GRID_TEACHER_TENSOR_PARALLEL_SIZE}" \
   TEACHER_MEM_FRACTION_STATIC="${GRID_TEACHER_MEM_FRACTION_STATIC}" \
   TEACHER_TEMPERATURE="${GRID_TEACHER_TEMPERATURE}" \
   ROLLOUT_TEMPERATURE="${GRID_ROLLOUT_TEMPERATURE}" \
   ROLLOUT_LABEL_KEY="${GRID_ROLLOUT_LABEL_KEY}" \
   STUDENT_LOAD="${STUDENT_LOAD:-}" \
   STUDENT_CKPT_STEP="${STUDENT_CKPT_STEP:-}" \
   REF_CKPT_STEP="${REF_CKPT_STEP:-}" \
   TEACHER_DATA_PARALLEL_SIZE="${TEACHER_DATA_PARALLEL_SIZE:-}" \
   APPLY_CHAT_TEMPLATE_KWARGS="${APPLY_CHAT_TEMPLATE_KWARGS:-}" \
   ROLLOUT_STOP_TOKEN_IDS="${ROLLOUT_STOP_TOKEN_IDS:-}" \
   ROLLOUT_SAMPLE_FILTER_PATH="${ROLLOUT_SAMPLE_FILTER_PATH:-}" \
   DYNAMIC_SAMPLING_SAMPLE_FILTER_PATH="${DYNAMIC_SAMPLING_SAMPLE_FILTER_PATH:-}" \
   DYNAMIC_SAMPLING_MAX_GENERATED_SAMPLES="${DYNAMIC_SAMPLING_MAX_GENERATED_SAMPLES:-}" \
   OPD_STUDENT_EOS_TOKEN_ID="${OPD_STUDENT_EOS_TOKEN_ID:-}" \
   OPD_TEACHER_EOS_TOKEN_ID="${OPD_TEACHER_EOS_TOKEN_ID:-}" \
   NUM_ROLLOUT="${GRID_NUM_ROLLOUT_VALUE}" \
   bash "${BASE_SCRIPT}" "$@"
}

grid_main() {
   grid_parse_args "$@"
   grid_validate_experiment

   if [ "${DRY_RUN}" = "1" ]; then
      grid_print_dry_run
      grid_run_experiment --dry-run
   else
      echo "=== Running exp_${GRID_EXP_INDEX}: Data=${DATA_LABEL} Teacher=${TEACHER_LABEL} Student=${STUDENT_LABEL} ==="
      grid_run_experiment
   fi
}
